version: '3'
services:
  fe_secret_santa:
    container_name: secret_santa_fe
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./frontend/:/app

  be_secret_santa:
    container_name: secret_santa_be
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/var/www/html/
      - ./backend/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./backend/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db

  db:
    container_name: secret_santa_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: "secret_santa"
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    container_name: secret_santa_phpmyadmin
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    depends_on:
      - db
